### ISSUE TITLE
Package details crashes

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#105] opened 2024-07-09 12:15 UTC
Steps to reproduce:

1. Click on "SBOMs"
2. Click on one SBOM
3. Click on the "Packages" tab
4. Open a collapsed package
5. 🔥

![image](https://github.com/trustification/trustify-ui/assets/202474/c8da5c5c-4996-4581-ad2d-c4999558ba6e)

**Comment by gildub** [comment] 2024-07-16 14:43
@ctron, I cannot reproduce it with latest. Could you please retry and if you can please provide the related data set.

**Comment by carlosthe19916** [comment] 2024-11-19 09:14
I can not reproduce the error either. Also the page "Sboms Details => Packages Tab" has changed dramatically compared to the version on the 9 July (when this issue was created). Now the page "Sboms Details => Packages Tab" is V1 compatible.

Closing this issue but we can reopen this if we discover the issue is still happening. Or we can also create a new one

**Closed** 2024-11-19 09:22 UTC
